"use strict";

Fingerprint.registerTest('navigator.parameters', function() {
    var knownProperties = [
        // 'clipboard',
        // 'credentials',
        // 'deviceMemory',
        // 'keyboard',
        // 'storage',
        // 'usb',
        'activeVRDisplays',
        'addIdleObserver',
        'appCodeName',
        'appName',
        'appVersion',
        'battery',
        'bluetooth',
        'budget',
        'buildID',
        'connection',
        'cookieEnabled',
        'credentials',
        'deviceMemory',
        'doNotTrack',
        'geolocation',
        'getBattery',
        'getGamepads',
        'getUserMedia',
        'getVRDisplays',
        'hardwareConcurrency',
        'language',
        'languages',
        'locks',
        'maxTouchPoints',
        'mediaCapabilities',
        'mediaDevices',
        'mimeTypes',
        'mozBluetooth',
        'mozIsLocallyAvailable',
        'mozNotification',
        'mozPay',
        'mozSocial',
        'mozTime',
        'onLine',
        'oscpu',
        'permissions',
        'platform',
        'plugins',
        'presentation',
        'product',
        'productSub',
        'registerContentHandler',
        'registerProtocolHandler',
        'requestMediaKeySystemAccess',
        'requestWakeLock',
        'securitypolicy',
        'sendBeacon',
        'serviceWorker',
        'share',
        'standalone',
        'storageQuota',
        'taintEnabled',
        'userAgent',
        'vendor',
        'vendorSub',
        'vibrate',
        'webkitNotification',
        'webkitPersistentStorage',
        'webkitPointer',
        'webkitTemporaryStorage',
    ]
    return propertyExistenceToBinary(navigator, knownProperties)
});
